import { Tr } from "dialogs/tr.slint";
import { ConfirmDialog, ErrorDialog, MessageDialog, ProgressDialog } from "dialogs/simple.slint";
import { ListPickerDialog, PickerItem, SearchListDialog } from "dialogs/picker.slint";
import { InfoDialog } from "dialogs/info.slint";

export { ConfirmDialog, ErrorDialog, InfoDialog, ListPickerDialog, MessageDialog, PickerItem, ProgressDialog, SearchListDialog, Tr }
